# Generated by Django 4.0.6 on 2023-07-23 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_country_region_unversity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unversity',
            name='image',
        ),
        migrations.AddField(
            model_name='faculty',
            name='unversetit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.unversity'),
        ),
    ]
