# Generated by Django 4.0.6 on 2023-07-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_remove_unversity_image_faculty_unversetit'),
    ]

    operations = [
        migrations.AddField(
            model_name='unversity',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
