# Generated by Django 4.0.6 on 2023-07-23 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_unversity_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='unversetit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.unversity'),
        ),
    ]
