# Generated by Django 4.0.6 on 2023-07-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_alter_faculty_unversetit'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='region',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
