# Generated by Django 4.0.6 on 2023-07-18 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_alter_students_age_alter_students_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='gender',
            field=models.CharField(choices=[('son1', 'son'), ('girl1', 'girl')], default='girl', max_length=5),
        ),
    ]
